"""add repository logs table

Revision ID: 363934cc1ba2
Revises: 9c833115de8a
Create Date: 2024-09-03 12:55:00.253604

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '363934cc1ba2'
down_revision: Union[str, None] = '9c833115de8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('repository_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('repository_name', sa.String(length=255), nullable=False),
    sa.Column('repository_type', sa.Enum('PERSONAL_REPO', 'ORGANISATION_REPO', name='repositorytype'), nullable=False),
    sa.Column('repository_url', sa.String(length=255), nullable=False),
    sa.Column('pickle_file', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_repository_logs_id'), 'repository_logs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_repository_logs_id'), table_name='repository_logs')
    op.drop_table('repository_logs')
    # ### end Alembic commands ###
